# Generated by Django 3.2.6 on 2023-06-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_man', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.IntegerField(choices=[(0, 'LOW'), (1, 'MEDIUM'), (2, 'HIGH')], null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')], null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='submitConfirm',
            field=models.IntegerField(choices=[(0, 'YES'), (1, 'NO')], null=True),
        ),
    ]
