# Generated by Django 3.2.6 on 2023-06-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./default_faculty.png', upload_to='profile_pics'),
        ),
    ]
